### ISSUE TITLE
Can't loop a sound effect without a while loop

### ISSUE THREAD

**Issue by guighub** [devkitPro/maxmod#9]
Is there a method for looping a sound sample without using a programmatic loop? I have a loop already that can't be used, or else the sound will overlap on every loop.

**Comment by fincs** [comment]
Modify your .wav file to contain a loop point, and it will be honored by mmutil. The [basic_sound](https://github.com/devkitPro/gba-examples/tree/master/audio/maxmod/basic_sound) example shows how to do it.

**Comment by exelotl** [comment]
This functionality was actually slightly broken (due to a logic error in `mmutil` which would cause the loop points to be ignored depending on what software you used to produce the WAV file).

This PR fixes it: https://github.com/devkitPro/mmutil/pull/6
